name: Build and Push Laravel Docker Image

on:
  push:
    branches:
      - "**" # This will trigger on all branches

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Image Name
        run: echo "IMAGE_NAME=petawilson/laravel-${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker Image to Docker Hub
        run: docker push $IMAGE_NAME
